import json

with open("All_Data/Colab_SAE_Data_Analysis.ipynb", "r") as f:
    nb = json.load(f)

new_cells = [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Deep Checkpoint Analysis (Weight Norms, Birth/Death, CKA)\n",
    "Here we download the actual `.pt` checkpoints to analyze weight drift, feature birth/death, and mutual orthogonality."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import torch\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from scipy.optimize import linear_sum_assignment\n",
    "\n",
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "\n",
    "# Clone the HF repo to get the .pt files if they don't exist locally\n",
    "if not os.path.exists(\"sae-rl-qwen05b-layers\"):\n",
    "    !GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/OhhMoo/sae-rl-qwen05b-layers\n",
    "\n",
    "base_path = \"sae-rl-qwen05b-layers\"\n",
    "layer_dirs = [\"layer6\", \"layer12\", \"layer18\", \"layer23\"]\n",
    "\n",
    "all_results = []\n",
    "print(\"Extracting statistics from checkpoint weights...\\n\")\n",
    "for layer in layer_dirs:\n",
    "    layer_path = os.path.join(base_path, layer)\n",
    "    if os.path.exists(layer_path):\n",
    "        pt_files = glob.glob(os.path.join(layer_path, \"*.pt\"))\n",
    "        for pt_file in pt_files:\n",
    "            file_name = os.path.basename(pt_file)\n",
    "            ckpt = torch.load(pt_file, map_location=\"cpu\", weights_only=False)\n",
    "            row = {'layer': layer, 'file_name': file_name}\n",
    "            \n",
    "            if \"step\" in file_name:\n",
    "                try:\n",
    "                    row['step'] = int(file_name.split(\"step\")[1].split(\"_\")[0].split(\".\")[0])\n",
    "                    row['model_type'] = \"ppo\"\n",
    "                except:\n",
    "                    row['step'] = None\n",
    "            else:\n",
    "                row['step'] = 0\n",
    "                row['model_type'] = \"base\"\n",
    "                \n",
    "            state_dict = ckpt['state_dict'] if 'state_dict' in ckpt else ckpt\n",
    "            row['encoder_weight_norm'] = state_dict.get('encoder.weight', state_dict.get('W_enc', torch.tensor(0.0))).norm().item() if any(k in state_dict for k in ['encoder.weight', 'W_enc']) else 0.0\n",
    "            row['decoder_weight_norm'] = state_dict.get('decoder.weight', state_dict.get('W_dec', torch.tensor(0.0))).norm().item() if any(k in state_dict for k in ['decoder.weight', 'W_dec']) else 0.0\n",
    "            all_results.append(row)\n",
    "\n",
    "combined_df = pd.DataFrame(all_results)\n",
    "if not combined_df.empty:\n",
    "    combined_df = combined_df.sort_values(by=['layer', 'step']).reset_index(drop=True)\n",
    "    display(combined_df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if not combined_df.empty:\n",
    "    summary_stats = combined_df.groupby(['layer', 'model_type']).agg(\n",
    "        avg_encoder_norm=('encoder_weight_norm', 'mean'),\n",
    "        avg_decoder_norm=('decoder_weight_norm', 'mean'),\n",
    "        max_step=('step', 'max')\n",
    "    ).reset_index()\n",
    "    print(\"Summary of Norms by Layer:\")\n",
    "    display(summary_stats)\n",
    "\n",
    "    base_models = combined_df[combined_df['model_type'] == 'base'].set_index('layer')\n",
    "    ppo_models_drift = combined_df[combined_df['model_type'] == 'ppo'].copy()\n",
    "    \n",
    "    def get_base_norm(layer_name):\n",
    "        return base_models.loc[layer_name, 'encoder_weight_norm'] if layer_name in base_models.index else None\n",
    "\n",
    "    ppo_models_drift['base_encoder_norm'] = ppo_models_drift['layer'].apply(get_base_norm)\n",
    "    ppo_models_drift['encoder_norm_diff'] = ppo_models_drift['encoder_weight_norm'] - ppo_models_drift['base_encoder_norm']\n",
    "    display(ppo_models_drift[['layer', 'step', 'encoder_weight_norm', 'encoder_norm_diff']].head())\n",
    "\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "    sns.lineplot(data=ppo_models_drift, x=\"step\", y=\"encoder_weight_norm\", hue=\"layer\", marker=\"o\", ax=axes[0])\n",
    "    axes[0].set_title('Encoder Weight Norm across RL Steps')\n",
    "    \n",
    "    sns.barplot(data=ppo_models_drift, x=\"layer\", y=\"encoder_norm_diff\", hue=\"layer\", errorbar='sd', ax=axes[1])\n",
    "    axes[1].set_title('Encoder Drift (Norm Difference vs Base Model)')\n",
    "    plt.tight_layout()\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "BIRTH_DEATH_THRESHOLD = 0.7\n",
    "\n",
    "def get_normalized_decoder_features(state_dict):\n",
    "    if 'decoder.weight' in state_dict:\n",
    "        W_dec = state_dict['decoder.weight']\n",
    "    elif 'W_dec' in state_dict:\n",
    "        W_dec = state_dict['W_dec']\n",
    "    else:\n",
    "        return None\n",
    "    return torch.nn.functional.normalize(W_dec, p=2, dim=0).cpu().numpy()\n",
    "\n",
    "def match_features_hungarian(sim_matrix, threshold=BIRTH_DEATH_THRESHOLD):\n",
    "    cost_matrix = 1.0 - np.abs(sim_matrix) \n",
    "    row_ind, col_ind = linear_sum_assignment(cost_matrix)\n",
    "    matched_sims = sim_matrix[row_ind, col_ind]\n",
    "    good_matches = np.abs(matched_sims) >= threshold\n",
    "    n_matched = good_matches.sum()\n",
    "    n_features_a, n_features_b = sim_matrix.shape\n",
    "    return {\n",
    "        \"n_matched\": int(n_matched),\n",
    "        \"n_births\": len(set(range(n_features_b)) - set(col_ind[good_matches])),\n",
    "        \"n_deaths\": len(set(range(n_features_a)) - set(row_ind[good_matches])),\n",
    "        \"mean_matched_sim\": float(np.abs(matched_sims[good_matches]).mean()) if n_matched > 0 else 0.0\n",
    "    }\n",
    "\n",
    "birth_death_results = []\n",
    "for layer in layer_dirs:\n",
    "    layer_files = combined_df[combined_df['layer'] == layer].sort_values(by='step') if not combined_df.empty else []\n",
    "    if len(layer_files) <= 1: continue\n",
    "    \n",
    "    W_dec_a = get_normalized_decoder_features(torch.load(os.path.join(base_path, layer, layer_files.iloc[0]['file_name']), map_location=\"cpu\", weights_only=False).get('state_dict', {}))\n",
    "    if W_dec_a is None: continue\n",
    "        \n",
    "    for i in range(1, len(layer_files)):\n",
    "        curr_file_row = layer_files.iloc[i]\n",
    "        W_dec_b = get_normalized_decoder_features(torch.load(os.path.join(base_path, layer, curr_file_row['file_name']), map_location=\"cpu\", weights_only=False).get('state_dict', {}))\n",
    "        if W_dec_b is not None:\n",
    "            match_result = match_features_hungarian(W_dec_a.T @ W_dec_b)\n",
    "            result = {\"layer\": layer, \"step_to\": curr_file_row['step'], \"n_births\": match_result['n_births'], \"n_deaths\": match_result['n_deaths'], \"n_matched\": match_result['n_matched']}\n",
    "            birth_death_results.append(result)\n",
    "            W_dec_a = W_dec_b\n",
    "\n",
    "if birth_death_results:\n",
    "    birth_death_df = pd.DataFrame(birth_death_results)\n",
    "    layer_df = birth_death_df[birth_death_df['layer'] == 'layer18']\n",
    "    if not layer_df.empty:\n",
    "        plt.figure(figsize=(10, 4))\n",
    "        plt.plot(layer_df[\"step_to\"], layer_df[\"n_births\"], \"o-\", label=\"Births\", color=\"green\")\n",
    "        plt.plot(layer_df[\"step_to\"], layer_df[\"n_deaths\"], \"s-\", label=\"Deaths\", color=\"red\")\n",
    "        plt.plot(layer_df[\"step_to\"], layer_df[\"n_matched\"], \"^-\", label=\"Persisted\", color=\"blue\")\n",
    "        plt.title(\"Feature Birth & Death (Layer 18)\")\n",
    "        plt.legend()\n",
    "        plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def linear_CKA(X, Y):\n",
    "    if X.shape != Y.shape: return 0.0\n",
    "    X, Y = X - X.mean(axis=0), Y - Y.mean(axis=0)\n",
    "    denom = np.linalg.norm(X.T @ X, \"fro\") * np.linalg.norm(Y.T @ Y, \"fro\")\n",
    "    return float(np.linalg.norm(Y.T @ X, \"fro\") ** 2 / denom) if denom != 0 else 0.0\n",
    "\n",
    "if not combined_df.empty:\n",
    "    layer_files = combined_df[combined_df['layer'] == 'layer18'].sort_values(by='step')\n",
    "    W_decs, ordered = {}, []\n",
    "    for _, row in layer_files.iterrows():\n",
    "        W_dec = get_normalized_decoder_features(torch.load(os.path.join(base_path, \"layer18\", row['file_name']), map_location=\"cpu\", weights_only=False).get('state_dict', {}))\n",
    "        if W_dec is not None:\n",
    "            W_decs[f\"Step {row['step']}\"] = W_dec\n",
    "            ordered.append(f\"Step {row['step']}\")\n",
    "            \n",
    "    n = len(ordered)\n",
    "    if n > 1:\n",
    "        cka_matrix = np.zeros((n, n))\n",
    "        for i in range(n):\n",
    "            for j in range(i, n):\n",
    "                cka_matrix[i, j] = cka_matrix[j, i] = linear_CKA(W_decs[ordered[i]], W_decs[ordered[j]])\n",
    "        \n",
    "        plt.figure(figsize=(6, 5))\n",
    "        im = plt.imshow(cka_matrix, cmap=\"YlOrRd\", vmin=0, vmax=1, aspect=\"auto\")\n",
    "        plt.xticks(range(n), ordered, rotation=45, ha=\"right\")\n",
    "        plt.yticks(range(n), ordered)\n",
    "        plt.title(\"CKA Matrix (Layer 18 SAE Decoders)\")\n",
    "        plt.colorbar(im)\n",
    "        plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_weight_norm_distributions(layer_folder):\n",
    "    layer_df = combined_df[combined_df['layer'] == layer_folder].sort_values('step') if not combined_df.empty else []\n",
    "    if len(layer_df) == 0: return\n",
    "    plt.figure(figsize=(8, 5))\n",
    "    colors = sns.color_palette(\"viridis\", n_colors=len(layer_df))\n",
    "    for i, (_, row) in enumerate(layer_df.iterrows()):\n",
    "        state_dict = torch.load(os.path.join(base_path, layer_folder, row['file_name']), map_location='cpu').get('state_dict', {})\n",
    "        w_dec = state_dict.get(\"W_dec\", state_dict.get(\"decoder.weight\", {}))\n",
    "        if hasattr(w_dec, 'T'):\n",
    "            if 'decoder.weight' in state_dict: w_dec = w_dec.T\n",
    "            norms = torch.norm(w_dec.float(), p=2, dim=-1)\n",
    "            sns.kdeplot(norms.numpy(), color=colors[i], label=f\"Step {row['step']}\", alpha=0.7)\n",
    "    plt.title(f\"Decoder Norm Distribution ({layer_folder})\")\n",
    "    plt.legend()\n",
    "    plt.show()\n",
    "\n",
    "plot_weight_norm_distributions(\"layer18\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_mutual_orthogonality(layer_folder):\n",
    "    layer_df = combined_df[combined_df['layer'] == layer_folder].sort_values('step') if not combined_df.empty else []\n",
    "    if len(layer_df) == 0: return\n",
    "    steps, orthos = [], []\n",
    "    for i, (_, row) in enumerate(layer_df.iterrows()):\n",
    "        state_dict = torch.load(os.path.join(base_path, layer_folder, row['file_name']), map_location='cpu').get('state_dict', {})\n",
    "        w_dec = state_dict.get(\"W_dec\", state_dict.get(\"decoder.weight\", {}))\n",
    "        if hasattr(w_dec, 'float'):\n",
    "            if 'decoder.weight' in state_dict: w_dec = w_dec.T\n",
    "            w_dec = w_dec.float()\n",
    "            w_norm = w_dec / torch.norm(w_dec, p=2, dim=-1, keepdim=True)\n",
    "            indices = torch.randperm(w_norm.shape[0])[:min(2000, w_norm.shape[0])]\n",
    "            w_sample = w_norm[indices]\n",
    "            sim_matrix = torch.matmul(w_sample, w_sample.T)\n",
    "            sim_matrix.fill_diagonal_(0)\n",
    "            steps.append(row['step'])\n",
    "            orthos.append(torch.mean(torch.abs(sim_matrix)).item())\n",
    "            \n",
    "    if steps:\n",
    "        plt.figure(figsize=(7, 4))\n",
    "        plt.plot(steps, orthos, marker='o', color='purple')\n",
    "        plt.title(f\"Mutual Orthogonality/Entanglement ({layer_folder})\")\n",
    "        plt.show()\n",
    "\n",
    "plot_mutual_orthogonality(\"layer18\")"
   ]
  }
]

nb["cells"].extend(new_cells)

with open("All_Data/Colab_SAE_Data_Analysis.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

